version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT_1://kafka:9093,PLAINTEXT_2://:9092,
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT_1://kafka:9093,PLAINTEXT_2://127.0.0.1:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT_1:PLAINTEXT,PLAINTEXT_2:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT_1
    depends_on:
      - zookeeper
  kowl:
    image: quay.io/cloudhut/kowl:master
    ports:
      - "8081:8080"
    environment:
      - KAFKA_BROKERS=kafka:9093
    depends_on:
      - kafka
    restart: always

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
